Improve pre-commit hook

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -33,8 +33,10 @@ do
 	then
 		which astyle > /dev/null || continue
 		OUT="${F}.formatted"
-		astyle < $F > $OUT
-		if [ "$(diff $F $OUT)" != "0" ]
+		astyle --options=$CPPOPTIONS < $F > $OUT
+		diff $F $OUT > /dev/null
+		R=$?
+		if [ "$R" != "0" ]
 		then
 			if [ $COUNT -eq 0 ]; then echo "Please check these files for coding convention:"; fi
 			let COUNT++
@@ -47,7 +49,8 @@ done
 
 # do not commit bad commit (can be forced with git commit -n)
 if [ "$COUNT" != "0" ]; then
-	echo "Commit aborted due to bad code formatting. Please fix! (-n forces commit)."
+	echo "Commit aborted due to bad code formatting."
+	echo "Please fix and do a git add again! (-n forces commit)."
 fi
 exit $COUNT
 
